Update User model attributes and references
Batch-738-Mathew-Oberlies/RideshareFrontend pull request #16
Opened 2020-05-02 02:15 UTC by flacks

User model fields prepended with `is` in the back-end were being received without `is`. Additionally, `hAddress` was being received with a lower-case `a`, as was `wAddress`. We've dropped the `is` from back-end model fields, and went with `homeAddress` and `workAddress` to work around this issue and improve code readability. This PR is done in tandem with the back-end change, and all old front-end model attribute references app-wide have been updated to match this update.

2020-05-02 04:21 UTC, IkenoXamos requested changes

2020-05-02 04:21 UTC, IkenoXamos commented on src/app/models/user.ts
>      hAddress: Address;
Shouldn't this be homeAddress?

2020-05-02 04:21 UTC, IkenoXamos commented on src/app/models/user.ts
>      wAddress: Address;
Shouldn't this be workAddress

2020-05-02 16:02 UTC, flacks commented on src/app/models/user.ts
>      hAddress: Address;
Thanks for pointing this out. Resolved.

2020-05-02 16:02 UTC, flacks commented on src/app/models/user.ts
>      wAddress: Address;
This one, too.

2020-05-02 16:03 UTC, flacks commented
Cherry-picked all the model changes. Project tested to build and function.

2020-05-02 16:13 UTC, flacks commented
Added update to the `Trip` model.

2020-05-04 13:51 UTC, IkenoXamos approved these changes

2020-05-04 15:23 UTC, merged